name: wind_turbine_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8            # Preferred Python version
  - jupyter               # Jupyter Notebook
  - pandas                # Data analysis library
  - ipykernel             # Allows the Conda environment to appear as a Jupyter kernel
  - notebook              # Jupyter Notebook interface
  - numpy                 # Numerical computations
  - matplotlib            # Basic plotting (optional)
